FROM almalinux:9
ARG course="Devops" \
    duration="120 Hrs"
ENV course-env="Devops" \
    author="siva" \
    duration-env="120 Hrs"
RUN echo course:$course, duration: $duration, author: $author, course-env: ${course-env}, duration-env: ${duration-env}
CMD [ "sleep", "100" ]